server:
  name: "project-user"
  Addr: "127.0.0.1:8080"
zap:
  debugFileName: "E:\\Codes\\GoProjects\\ms_project\\logs\\debug\\project-debug.log"
  infoFileName: "E:\\Codes\\GoProjects\\ms_project\\logs\\debug\\project-info.log"
  warnFileName: "E:\\Codes\\GoProjects\\ms_project\\logs\\debug\\project-error.log"
  maxSize: 10
  maxAge: 28
  MaxBackups: 2
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
grpc:
  name: "user"
  addr: "127.0.0.1:8881"
  version: "1.0.0"
  weight: 2  # 和etcd负载均衡，backend的权重相关；
etcd:
  Addrs:
    - "127.0.0.1:2379"
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3309
  db: msproject
